#
# Cleanup bad-ansible with Roles
- name: Run common tasks
  hosts: all
  roles:
    - common

- name: Run application server tasks
  hosts: apps
  roles:
    - tomcat
    - app
    - apache

- name: Run frontend tasks
  hosts: frontends
  roles:
    - haproxy

- name: Run DB tasks
  hosts: appdbs
  roles:
    - postgres
